const fs = require('fs');
const path = require('path');
const { program } = require('commander');
const officegen = require('officegen');

program
  .option('--output <file>', 'Output file path')
  .option('--title <title>', 'Document title')
  .option('--content <text>', 'Markdown-like content')
  .parse(process.argv);

const options = program.opts();

async function createDocx() {
    const docx = officegen('docx');
    
    // Add Metadata
    docx.setDocTitle(options.title || 'Generated Doc');
    docx.setDescription('Generated by OpenClaw');

    // Add Content
    const pObj = docx.createP();
    pObj.addText(options.title || 'Document', { font_face: 'Arial', font_size: 24, bold: true });
    pObj.addLineBreak();
    
    if (options.content) {
        const lines = options.content.split('\\n');
        for (const line of lines) {
            const para = docx.createP();
            if (line.startsWith('# ')) {
                para.addText(line.substring(2), { font_size: 18, bold: true, color: '2E74B5' });
            } else if (line.startsWith('## ')) {
                para.addText(line.substring(3), { font_size: 14, bold: true, color: '1F4D78' });
            } else if (line.startsWith('- ')) {
                para.addText('• ' + line.substring(2));
            } else {
                para.addText(line);
            }
        }
    }

    const out = fs.createWriteStream(options.output || 'out.docx');
    
    out.on('error', function(err) {
        console.log(err);
    });

    docx.generate(out);
    console.log('DOCX generated successfully');
}

createDocx();
